//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckZOVReminder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".button.suggest2-form__button.button_size_m.button_theme_normal.i-bem.button_js_i" +
            "nited")]
        public string XPathButton {
            get {
                return ((string)(this["XPathButton"]));
            }
            set {
                this["XPathButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::div[contains(@class, \'serp-block serp-block-\')]")]
        public string XPathBlockLinksName {
            get {
                return ((string)(this["XPathBlockLinksName"]));
            }
            set {
                this["XPathBlockLinksName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../descendant-or-self::a[contains(@class, \'b-link serp-url__link\')]")]
        public string XPathUrl0 {
            get {
                return ((string)(this["XPathUrl0"]));
            }
            set {
                this["XPathUrl0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::a[contains(@class, \'b-link serp-url__link\')]")]
        public string XPathUrl1 {
            get {
                return ((string)(this["XPathUrl1"]));
            }
            set {
                this["XPathUrl1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../../descendant-or-self::div[contains(@class, \'serp-item__text\')]")]
        public string XPathDescription0 {
            get {
                return ((string)(this["XPathDescription0"]));
            }
            set {
                this["XPathDescription0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::div[contains(@class, \'serp-item__text\')]")]
        public string XPathDescription1 {
            get {
                return ((string)(this["XPathDescription1"]));
            }
            set {
                this["XPathDescription1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/descendant-or-self::input[contains(@name, \'person\')]")]
        public string XPathCheckMyStorySearch {
            get {
                return ((string)(this["XPathCheckMyStorySearch"]));
            }
            set {
                this["XPathCheckMyStorySearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/descendant-or-self::input[contains(@name, \'save\')]")]
        public string XPathButtonsSaveSettings {
            get {
                return ((string)(this["XPathButtonsSaveSettings"]));
            }
            set {
                this["XPathButtonsSaveSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--yadirect")]
        public string CommandYaDirect {
            get {
                return ((string)(this["CommandYaDirect"]));
            }
            set {
                this["CommandYaDirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--all")]
        public string CommandAll {
            get {
                return ((string)(this["CommandAll"]));
            }
            set {
                this["CommandAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--excel")]
        public string CommandExcel {
            get {
                return ((string)(this["CommandExcel"]));
            }
            set {
                this["CommandExcel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--relatedwords")]
        public string CommandRelatedWords {
            get {
                return ((string)(this["CommandRelatedWords"]));
            }
            set {
                this["CommandRelatedWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--storetodb")]
        public string CommandStoreToDB {
            get {
                return ((string)(this["CommandStoreToDB"]));
            }
            set {
                this["CommandStoreToDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--pageamounts")]
        public string CommandPageAmounts {
            get {
                return ((string)(this["CommandPageAmounts"]));
            }
            set {
                this["CommandPageAmounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--autorun")]
        public string CommandAutoRun {
            get {
                return ((string)(this["CommandAutoRun"]));
            }
            set {
                this["CommandAutoRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("--autoclose")]
        public string CommandAutoClose {
            get {
                return ((string)(this["CommandAutoClose"]));
            }
            set {
                this["CommandAutoClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("region-change__content")]
        public string RegionChange {
            get {
                return ((string)(this["RegionChange"]));
            }
            set {
                this["RegionChange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::div[contains(@class, \'serp-adv__block serp-adv\')]")]
        public string XPathDirect {
            get {
                return ((string)(this["XPathDirect"]));
            }
            set {
                this["XPathDirect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::a[contains(@class, \'b-link serp-item__title-link\')]")]
        public string XPathMain0 {
            get {
                return ((string)(this["XPathMain0"]));
            }
            set {
                this["XPathMain0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::a[contains(@class, \'b-link serp-item__title-link\')]")]
        public string XPathADVBlock {
            get {
                return ((string)(this["XPathADVBlock"]));
            }
            set {
                this["XPathADVBlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("descendant-or-self::div[contains(@class, \'serp-item__wrap clearfix\')]")]
        public string XPathMain1 {
            get {
                return ((string)(this["XPathMain1"]));
            }
            set {
                this["XPathMain1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("купить кухню\r\nкупить кухню в %C\r\nбелорусские кухни\r\nбелорусские кухни зов\r\nкухни " +
            "в %C\r\nкухни %C\r\nкухни зов\r\nкухни зов %C\r\nкухни на заказ\r\nкухни на заказ в %C нед" +
            "орого\r\nкухня\r\nкупить белорусскую кухню\r\nбелорусские кухни")]
        public string Words {
            get {
                return ((string)(this["Words"]));
            }
            set {
                this["Words"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\CheckZOVReminder\\chromedriver_win32")]
        public string ChromeDriverPath {
            get {
                return ((string)(this["ChromeDriverPath"]));
            }
            set {
                this["ChromeDriverPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Work\\CheckZOVReminder\\CheckZOVReminder\\Regions.xlsx")]
        public string PathToRegions {
            get {
                return ((string)(this["PathToRegions"]));
            }
            set {
                this["PathToRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Москва\r\nСанкт-Петербург\r\nТула\r\nТверь\r\nТольятти\r\nРязань\r\nНижний Новгород\r\n! Гурино" +
            "вич !\r\nЛипецк\r\nЯрославль\r\nКурск\r\nСамара")]
        public string Regions {
            get {
                return ((string)(this["Regions"]));
            }
            set {
                this["Regions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("button button_counter_yes button_pseudo_yes button_theme_pseudo button_size_s b-l" +
            "ink b-link_pseudo_yes i-bem button_js_inited")]
        public string NextButton {
            get {
                return ((string)(this["NextButton"]));
            }
            set {
                this["NextButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Следующая")]
        public string NextButtonText {
            get {
                return ((string)(this["NextButtonText"]));
            }
            set {
                this["NextButtonText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Регион")]
        public string RegionValue {
            get {
                return ((string)(this["RegionValue"]));
            }
            set {
                this["RegionValue"] = value;
            }
        }
    }
}
